version: "3.8"
services:

  php:
    image: php:8.1-fpm-alpine
    container_name: php
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8081:80"
    networks:
      - dev

  db:
    image: mysql
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
