FROM php:8.1-fpm-alpine

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN apk add --no-cache bash
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash
RUN apk add --no-cache symfony-cli
RUN apk add git

RUN set -ex \
    && apk --no-cache add \
    postgresql-dev

RUN docker-php-ext-install -j$(nproc) intl pdo mysqli pdo_mysql
RUN docker-php-ext-install sysvsem
RUN docker-php-ext-enable pdo_mysql

WORKDIR /app/