name: php-unit-github-actions
run-name: ${{ github.actor }} is launching phpunit github action
on: [push]
jobs:
  php-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16.x'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: php bin/phpunit